### ISSUE TITLE
Help for a noob, 

### ISSUE THREAD

**Issue by mattssn** [TwizzyDizzy/scripts#1]
Can you explain how to use this, I would love to utilize this and am a boot of a noob, I have koel installed and working fine, thanks.

**Comment by mattssn** [comment]
I guess I should specify, Trying to use your script to put music into playlists by folder.

**Comment by TwizzyDizzy** [comment]
Hey @mattssn 

well.. you have to adjust you path to koel in [line 17](https://github.com/TwizzyDizzy/scripts/blob/master/php/koel-playlists-from-folders/cron.php#L17) and then you have to specify [here](https://github.com/TwizzyDizzy/scripts/blob/master/php/koel-playlists-from-folders/cron.php#L20-L26) which folders you want to scan to create playlists from them. You can get your user id from the koel database.

And then you just run this script with PHP.

Cheers
Thomas

**Comment by mattssn** [comment]
```
# $folders array format:
# array(["koel_user-id-1"] => array("folder-foo","folder-bar","folder-foobar"),
$folders = array(
        "1" => array("Tracks","Mixes"),
        "3" => array("Tracks","Mixes"),
        );

```
Is there a way to make this just scan all folders? also my users table looks like this, 

![databas](https://user-images.githubusercontent.com/33325618/32409035-f04b0c84-c160-11e7-9059-97d4f2b9775a.png)

I am assuming that would just make my user id 1 right?

**Comment by TwizzyDizzy** [comment]
> I am assuming that would just make my user id 1 right?

Yes.

> Is there a way to make this just scan all folders?

Yes, yet it is not implemented in my script. That being said: doing that should be straight forward with a bit of PHP knowledge.

I'm assuming you want this to have a playlist for every album? But then why not search for a specific album and just hit play?

Cheers
Thomas

**Comment by mattssn** [comment]
> I'm assuming you want this to have a playlist for every album? But then why not search for a specific album and just hit play? Of course, this assumens that you have properly tagged your music files.

Yeah the one I have the music is not very organized, they are in folders like best of EDM 2018, best of EDM 2017 etc, they are not tagged and mixed genres and what not, I would just like to upload the folders, and have the different, folders made into playlists. 

Plex for example has a way to view by folder and just shuffle everything on the folder, the folders are read from the server media path structure.

**Comment by TwizzyDizzy** [comment]
> Yeah the way I have the music is not very organized, they are in folders like best of EDM 2018, best of EDM 2017 etc, they are not tagged and mixed genres and what not, I would just like to upload the folders, and have the different, folders made into playlists.

Well, as I said: it is possible to do that with a bit of PHP skills, but I do not intend to implement this in my script. You're of course welcome to take my script as a basis for your implementation.

> Plex for example has a way to view by folder and just shuffle everything on the folder, the folders are read from the server media path structure.

From what I gathered in discussions with the developer of koel, being like Plex (or any other software like it) is nothing he aims for.

Cheers
Thomas

**Comment by mattssn** [comment]
Yeah I don’t know PHP coding, I’ll just tag the files in those folders with the same album tag and just search in Koel for that album tag and throw them into the same playlist, I appreciate the help

**Comment by TwizzyDizzy** [comment]
Ah... yeah... that's in fact the easiest solution for your library, indeed. Didn't think of it, but should work :)

In fact... why do you even create a playlist from it. If you tag all files in a folder with the same album tag, you can simply browser your "albums"!

Cheers
Thomas

**Comment by mattssn** [comment]
Yeah, will work either way, just make a bit quicker to see my folder selections when I am trying to decide what to listen to, I know there are a few programs out there that make tagging multiple files at once easy. just have to find the best one to use, :P

**Comment by TwizzyDizzy** [comment]
[Ex Falso](https://en.wikipedia.org/wiki/Ex_Falso) works perfectly, for me :)

**Comment by mattssn** [comment]
You are the man, thank you so much for all the help with this, you won't believe how many issues I had getting Koel installed, took me a few days, main issue was getting the db through mariadb to work, I ended up switching to just regular mysql and it worked perfect, now to just get all my music the way I want it.
